enabled: False
hostname: disabled
rsync_username: autorsyncbackup
rsync_password: fee-fi-fo-fum
rsync_share: backup
ssh: False
ssh_sudo: False
ssh_username: autorsyncbackup
ssh_privatekey: /home/autorsyncbackup/.ssh/id_rsa
include: #formerly fileset
  - /etc
exclude:
  - "*.bak"
  - ".cache/*"
hooks:
  - script: uptime
    local: true
    runtime: before
    continueonerror: true

  - script: cat /etc/motd
    local: false
    runtime: after
    continueonerror: true
